### ISSUE TITLE
the ability to disable the display of standard slots(armor and hands) in the config

### ISSUE THREAD

**Issue by DannikInfo** [AlonsoAliaga/BetterProfiles#1]
I think it would be nice because the plugin is good, but in the current version, unfortunately, this cannot be done :(

**Comment by AlonsoAliaga** [comment]
You probably solved this issue already, but in case someone reading this is having the same issue you can set the number of the slots you want to disable to the same slot the "close" button has. You MUST disable "Update-equipement" option. This will prevent the close button from being overwritten in case player updates inventory.

Open issue if you are still having problems.
