### ISSUE TITLE
Status placeholders for /betterprofile toggle

### ISSUE THREAD

**Issue by thatpris** [AlonsoAliaga/BetterProfiles#2]
NOTICE THAT THIS IS JUST A REQUEST. FEATURE CAN NEVER BE ADDED.

**Is your feature request related to a problem? Please describe.**
I'm making a setting GUI with DeluxeMenu, and I need to retrieve the status of the toggle feature so I can add the enabled and disabled message correspondingly. However as far as I know there is no placeholders for this plugin.

**Describe the solution you'd like**
Add placeholders like %betterprofiles_profile_seeing_status% and %betterprofiles_profile_beingseen_status% or that sort.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AlonsoAliaga** [comment]
Doesnt sound bad to me. However I can't update the plugin for now. Reason: I heavily modified the code before to make an update but I didn't finish it (that was months ago) so I have to recheck the code to k ñnow what i did and finish it before I can even think about adding new features sorry. As mentioned, can be added, but won't be done until I finish the update.  No ETA as I don't even remember what I did until I resume the development of that plugin

**Comment by AlonsoAliaga** [comment]
Added in 1.6-BETA if i recall correctly
