### ISSUE TITLE
Poder quitar el boton de exit

### ISSUE THREAD

**Issue by Scrulius** [AlonsoAliaga/BetterProfiles#3]
Buenas Alonso!

Me encanta BetterProfiles, el unico problema que veo es que no puedes desactivar el boton de exit, sería fantastico si pudiera hacerlo

Mil gracias!

**Comment by AlonsoAliaga** [comment]
Hola, desafortunadamente este plugin no será actualizado pronto por temas personales.
Para desactivar el slot debes setearlo como -1 y de preferencia reiniciar el servidor.

Confirma para poder cerrar el ticket. Buen día!

**Comment by Scrulius** [comment]
Listo, gracias!
