### ISSUE TITLE
Unable to display icon "BREWING_STAND"

### ISSUE THREAD

**Issue by BBDL233** [AlonsoAliaga/BetterProfiles#5]
**Describe the bug**
Unable to display icon "BREWING_STAND"
Perhaps there are more

**To Reproduce**
1.download BetterProfiles-v1.6-BETA.jar Put it in plugins
2.download NBTAPI.jar Put it in plugins
3.run paper 1.8.8
4.set items.yml:
![image](https://github.com/AlonsoAliaga/BetterProfiles/assets/99265367/32904147-2e44-4152-8afe-35655704be7b)
5.reload plugin

**Expected behavior**
He should display it normally, like this (paper 1.20.4)
![image](https://github.com/AlonsoAliaga/BetterProfiles/assets/99265367/394f5cdb-7d09-4ebc-860b-bf1555629982)

**Screenshots**
But 1.8.8
![image](https://github.com/AlonsoAliaga/BetterProfiles/assets/99265367/2fee2693-6bbf-40ae-8977-5ac5871785b3)

**Important (please complete the following information):**
 - Java version: 8
 - Plugin version: paper 1.8.8
 - Server version:
 - This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
 - Error obtaining version information
 
![image](https://github.com/AlonsoAliaga/AlonsoLevels/assets/99265367/26330eda-90a4-4468-a574-6e44ffb043d3)

**Additional context**
I'm sure my configuration is correct, it displays normally at 1.20.4
1.8.9:
![image](https://github.com/AlonsoAliaga/BetterProfiles/assets/99265367/55ce8962-9844-4c35-9740-6d0feb0c7f1d)

**Comment by AlonsoAliaga** [comment]
Have you tried BREWING_STAND_ITEM?

**Comment by BBDL233** [comment]
Problem Solving

**Comment by AlonsoAliaga** [comment]
Don't forget to check https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html specially when using realle old versions like 1.8.8, the ones that start with LEGACY_

**Comment by BBDL233** [comment]
I see. Thank you
